In [67]:
# Importando pandas e numpy
import pandas as pd
import numpy as np

In [68]:
# Criando variável da tabelaa ENEM 2024 já tratada
caminho_dados = '/content/drive/MyDrive/analise-diagnostico-enem2024/tabela_enem2024.csv'

In [ ]:
# Lendo arquivo da tabela
df = pd.read_csv(caminho_dados)

In [ ]:
# Exibindo pequena amostra
df.head()

,numero_seq_aluno,municipio,uf,dependencia,localizacao,nota_ciencias_naturais,nota_ciencias_humanas,nota_linguagens,nota_matematica,nota_redacao
0,206403,Aratuba,CE,Estadual,Urbana,436.8,377.8,423.4,427.1,300.0
1,3604651,Tijucas,SC,Privada,Urbana,521.9,601.9,605.5,689.2,920.0
2,1461268,Rolândia,PR,Não informado,Não informado,363.0,548.4,557.2,456.4,480.0
3,4301058,Osasco,SP,Não informado,Não informado,550.7,553.8,605.9,629.1,740.0
4,140768,Natal,RN,Não informado,Não informado,482.7,531.6,439.2,496.7,360.0

In [ ]:
# Exbindo tipos de dados
df.dtypes

numero_seq_aluno            int64
municipio                  object
uf                         object
dependencia                object
localizacao                object
nota_ciencias_naturais    float64
nota_ciencias_humanas     float64
nota_linguagens           float64
nota_matematica           float64
nota_redacao              float64
dtype: object

## Adicionando coluna de média por aluno

In [ ]:
# Calculando a média por aluno
df['media_geral'] = df[['nota_ciencias_naturais',
                        'nota_ciencias_humanas',
                        'nota_linguagens',
                        'nota_matematica',
                        'nota_redacao']].mean(axis=1).round(1)

In [ ]:
# Exibindo pequena amostra

,numero_seq_aluno,municipio,uf,dependencia,localizacao,nota_ciencias_naturais,nota_ciencias_humanas,nota_linguagens,nota_matematica,nota_redacao,media_geral
0,206403,Aratuba,CE,Estadual,Urbana,436.8,377.8,423.4,427.1,300.0,393.0
1,3604651,Tijucas,SC,Privada,Urbana,521.9,601.9,605.5,689.2,920.0,667.7
2,1461268,Rolândia,PR,Não informado,Não informado,363.0,548.4,557.2,456.4,480.0,481.0
3,4301058,Osasco,SP,Não informado,Não informado,550.7,553.8,605.9,629.1,740.0,615.9
4,140768,Natal,RN,Não informado,Não informado,482.7,531.6,439.2,496.7,360.0,462.0
...,...,...,...,...,...,...,...,...,...,...,...
2990088,2891903,Bragança,PA,Estadual,Rural,485.6,475.2,503.0,438.6,540.0,488.5
2990089,1966623,Brasília,DF,Não informado,Não informado,564.1,649.5,619.8,609.9,640.0,616.7
2990090,1661560,Araguaína,TO,Não informado,Não informado,455.2,436.2,440.2,503.2,420.0,451.0
2990091,2464303,Itapevi,SP,Estadual,Urbana,602.2,541.8,552.2,652.4,580.0,585.7
2990092,3131550,Campinas,SP,Não informado,Não informado,576.3,590.3,584.2,652.7,780.0,636.7

In [ ]:
# Checando de tipagem de dados
df.dtypes

numero_seq_aluno            int64
municipio                  object
uf                         object
dependencia                object
localizacao                object
nota_ciencias_naturais    float64
nota_ciencias_humanas     float64
nota_linguagens           float64
nota_matematica           float64
nota_redacao              float64
media_geral               float64
dtype: object

In [ ]:
# Salvando a tabela
df.to_csv('/content/drive/MyDrive/analise-diagnostico-enem2024/consultas/df_enem2024.csv', decimal=',',index=False)

## Calculando média por dependência

In [ ]:
# Coletando médias por escola dependência
df_media_dependencia = df.groupby('dependencia')['media_geral'].mean().round(2)

In [ ]:
# Ordenando do maior pro menor valor
df_media_dependencia = df_media_dependencia.sort_values(ascending = False).reset_index()

In [ ]:
df_media_dependencia.head()

     dependencia  media_geral
0        Privada       614.14
1        Federal       585.89
2      Municipal       544.92
3  Não informado       544.17
4       Estadual       505.17

In [ ]:
# Checando tipagem de dados
df_media_dependencia.dtypes

dependencia     object
media_geral    float64
dtype: object

In [ ]:
# Salvando df
df_media_dependencia.to_csv('/content/drive/MyDrive/analise-diagnostico-enem2024/consultas/df_media_por_dependencia.csv', decimal=',', index=False)

## Calculando média e desvio padrão por estado

In [ ]:
# Calculando média por estado
df_media_uf = df.groupby('uf')['media_geral'].mean().round(2).reset_index()

In [ ]:
# Calculando o desvio padrão e adicionando coluna a tabela
desvio_por_uf = df.groupby('uf')['media_geral'].std().round(2)
df_media_uf['desvio_padrao'] = df_media_uf['uf'].map(desvio_por_uf).round(2)

In [ ]:
# Exibindo amostra
df_media_uf.head()

   uf  media_geral  desvio_padrao
0  AC       514.20          83.40
1  AL       515.43          94.21
2  AM       499.52          86.02
3  AP       508.38          83.71
4  BA       518.08          88.83

In [ ]:
# Checando tipagem de dados
df_media_uf.dtypes

uf                object
media_geral      float64
desvio_padrao    float64
regiao            object
dtype: object

In [ ]:
# Salvando df
df_media_uf.to_csv('/content/drive/MyDrive/analise-diagnostico-enem2024/consultas/df_media_desvio_por_uf.csv', decimal=',', index=False)

## Calculando média e desvio padrão por região

In [ ]:
# Definindo listas de regiões
norte = ['AC', 'AP', 'AM', 'PA', 'RO', 'RR', 'TO']
nordeste = ['AL', 'BA', 'CE', 'MA', 'PB', 'PE', 'PI', 'RN', 'SE']
centro_oeste = ['DF', 'GO', 'MT', 'MS']
sudeste = ['ES', 'MG', 'RJ', 'SP']
sul = ['PR', 'RS', 'SC']

In [ ]:
# Criando função para identificar a região em que a UF está
regioes = {
    'N': norte,
    'NE': nordeste,
    'CO': centro_oeste,
    'SE': sudeste,
    'S': sul
}

def definir_regiao(uf):
    for regiao, lista_ufs in regioes.items():
        if uf in lista_ufs:
            return regiao
    return 'Desconhecida'  # caso o UF não esteja em nenhuma lista

In [ ]:
# Criando a coluna de identificação da região
df_media_uf['regiao'] = df_media_uf['uf'].apply(definir_regiao)

In [ ]:
# Exibindo pequena amostra
df_media_uf.head()

   uf  media_geral  desvio_padrao regiao
0  AC       514.20          83.40      N
1  AL       515.43          94.21     NE
2  AM       499.52          86.02      N
3  AP       508.38          83.71      N
4  BA       518.08          88.83     NE

In [ ]:
# Criando df de média por região
df_media_regiao = df_media_uf.groupby('regiao')['media_geral'].mean().round(2)

In [ ]:
# Ordenando da maior pra menor média
df_media_regiao = df_media_regiao.sort_values(ascending=False).reset_index()

In [ ]:
# Exibindo média por região
df_media_regiao

  regiao  media_geral
0     SE       559.56
1      S       554.43
2     CO       543.13
3     NE       524.10
4      N       511.92

In [ ]:
# Criando df de desvio padrão por região
df_desvio_por_regiao = df_media_uf.groupby('regiao')['media_geral'].std().round(2).rename('desvio_padrao')

In [ ]:
# Exibindo tabela
df_desvio_por_regiao

regiao
CO    14.51
N      7.59
NE     9.93
S      8.06
SE     4.54
Name: desvio_padrao, dtype: float64

In [ ]:
# Fazendo a junção das tabelas

df_media_e_desvio_por_regiao = df_media_regiao.merge(df_desvio_por_regiao,
                  how = 'inner',
                  left_on = ['regiao'],
                  right_on = ['regiao'])

In [ ]:
# Exibindo nova df de média e desvio por região
df_media_e_desvio_por_regiao

  regiao  media_geral  desvio_padrao
0     SE       559.56           4.54
1      S       554.43           8.06
2     CO       543.13          14.51
3     NE       524.10           9.93
4      N       511.92           7.59

In [ ]:
# Checando tipagem de daos
df_media_e_desvio_por_regiao.dtypes

regiao            object
media_geral      float64
desvio_padrao    float64
dtype: object

In [ ]:
# Salvando tabela
df_media_e_desvio_por_regiao.to_csv('/content/drive/MyDrive/analise-diagnostico-enem2024/consultas/df_media_desvio_por_regiao.csv', decimal=',', index=False)

## Calculando média e desvio de disciplinas por dependência

In [ ]:
# Criando a df com a media e desvio padrão de cada disciplina por dependência
df_media_desvio_disciplina_por_dependencia = df.groupby('dependencia')[['nota_ciencias_naturais',	'nota_ciencias_humanas',	'nota_linguagens', 'nota_matematica',	'nota_redacao']].agg(['mean', 'std']).round(2)

In [ ]:
# Resetando o índice da tabela
df_media_desvio_disciplina_por_dependencia = df_media_desvio_disciplina_por_dependencia.reset_index()

In [ ]:
# Exibindo colunas
df_media_desvio_disciplina_por_dependencia.columns

MultiIndex([(           'dependencia',     ''),
            ('nota_ciencias_naturais', 'mean'),
            ('nota_ciencias_naturais',  'std'),
            ( 'nota_ciencias_humanas', 'mean'),
            ( 'nota_ciencias_humanas',  'std'),
            (       'nota_linguagens', 'mean'),
            (       'nota_linguagens',  'std'),
            (       'nota_matematica', 'mean'),
            (       'nota_matematica',  'std'),
            (          'nota_redacao', 'mean'),
            (          'nota_redacao',  'std')],
           )

In [ ]:
# Achatando colunas do MultiIndex
df_media_desvio_disciplina_por_dependencia.columns = [
    f'{col[0]}_{col[1]}' for col in df_media_desvio_disciplina_por_dependencia.columns
]

In [ ]:
# Visualizando df
df_media_desvio_disciplina_por_dependencia

,dependencia_,nota_ciencias_naturais_mean,nota_ciencias_naturais_std,nota_ciencias_humanas_mean,nota_ciencias_humanas_std,nota_linguagens_mean,nota_linguagens_std,nota_matematica_mean,nota_matematica_std,nota_redacao_mean,nota_redacao_std
0,Estadual,466.20,64.63,481.89,81.20,503.36,65.16,489.73,88.88,584.68,217.46
1,Federal,528.28,73.99,544.90,83.46,551.25,58.15,579.39,113.55,725.64,169.86
2,Municipal,497.17,70.23,521.62,78.42,535.38,59.22,531.57,101.65,638.87,176.48
3,Não informado,498.92,80.31,521.19,92.07,531.80,68.22,531.34,116.21,637.60,203.65
4,Privada,549.08,77.69,570.89,83.49,565.48,58.36,616.30,119.65,768.96,149.64

In [ ]:
# Checando tipagem de dados
df_media_desvio_disciplina_por_dependencia.dtypes

dependencia_                    object
nota_ciencias_naturais_mean    float64
nota_ciencias_naturais_std     float64
nota_ciencias_humanas_mean     float64
nota_ciencias_humanas_std      float64
nota_linguagens_mean           float64
nota_linguagens_std            float64
nota_matematica_mean           float64
nota_matematica_std            float64
nota_redacao_mean              float64
nota_redacao_std               float64
dtype: object

In [ ]:
# Salvando df
df_media_desvio_disciplina_por_dependencia.to_csv('/content/drive/MyDrive/analise-diagnostico-enem2024/consultas/df_media_desvio_disciplina_por_dependencia.csv', decimal=',', index=False)

## Calculando porcentagem de alunos com acima de 600 pontos de média por estado

In [ ]:
# Definindo função de triagem
media = 600
def acima_media(x):
  if x > media:
    return True
  else:
    return False

In [ ]:
# Copiando a tabela principal
df2 = df.copy()

In [ ]:
# Criando coluna de identificação de limite da nota
df2['media_maior_que_600'] = df2['media_geral'].apply(acima_media)

In [ ]:
# Exibindo amostra da nova tabela
df2.head()

,numero_seq_aluno,municipio,uf,dependencia,localizacao,nota_ciencias_naturais,nota_ciencias_humanas,nota_linguagens,nota_matematica,nota_redacao,media_geral,media_maior_que_600
0,206403,Aratuba,CE,Estadual,Urbana,436.8,377.8,423.4,427.1,300.0,393.0,False
1,3604651,Tijucas,SC,Privada,Urbana,521.9,601.9,605.5,689.2,920.0,667.7,True
2,1461268,Rolândia,PR,Não informado,Não informado,363.0,548.4,557.2,456.4,480.0,481.0,False
3,4301058,Osasco,SP,Não informado,Não informado,550.7,553.8,605.9,629.1,740.0,615.9,True
4,140768,Natal,RN,Não informado,Não informado,482.7,531.6,439.2,496.7,360.0,462.0,False

In [ ]:
# Criando nova series com porcentagem de nota média acima de 600 pontos
porcentagem_media_600_por_estado = (df2.groupby('uf')['media_maior_que_600'].mean()*100).rename('porcentagem_acima_de_600')

In [ ]:
# Arredondando porcentagem para até duas casas decimais e ordenando do maior para o menor
porcentagem_media_600_por_estado = porcentagem_media_600_por_estado.round(2).sort_values(ascending=False).reset_index()

# Ajustando indice para começar em 1
porcentagem_media_600_por_estado.index += 1

In [ ]:
# Exibindo tabela
porcentagem_media_600_por_estado

    uf  porcentagem_acima_de_600
1   DF                     34.63
2   SP                     34.24
3   MG                     33.87
4   SC                     33.27
5   ES                     31.76
6   RJ                     31.26
7   PR                     27.80
8   RS                     27.38
9   GO                     26.66
10  CE                     24.52
11  RN                     24.51
12  MS                     23.32
13  PB                     22.58
14  PE                     22.11
15  MT                     21.94
16  SE                     21.82
17  PI                     19.44
18  AL                     18.85
19  RR                     18.72
20  TO                     18.41
21  BA                     18.22
22  RO                     16.65
23  AC                     15.74
24  MA                     14.55
25  PA                     14.52
26  AP                     13.80
27  AM                     12.73

In [ ]:
# Checando tipagem de dados
porcentagem_media_600_por_estado.dtypes

uf                           object
porcentagem_acima_de_600    float64
dtype: object

In [ ]:
# Salvando df
porcentagem_media_600_por_estado.to_csv('/content/drive/MyDrive/analise-diagnostico-enem2024/consultas/porcentagem_media600_por_estado.csv', decimal=',', index=False)

## Calculando quantidade de alunos com mais de 600 pontos

In [77]:
# Copiando a df principal para uma nova df
df3 = df.copy()

In [78]:
# Filtrando médias com mais de 600 pontos
media_600 = df3.loc[df3['media_geral'] > 600]

In [79]:
# Agrupando por UF
media_600 = media_600.groupby('uf')['media_geral'].count().reset_index()

In [80]:
# Renomeando coluna 'media_geral
media_600.rename(columns={'media_geral' : 'qtd_media_600'}, inplace=True)

In [81]:
# Exibindo amostra da tabela
media_600.head()

   uf  qtd_media_600
0  AC           2652
1  AL          11738
2  AM           6744
3  AP           2758
4  BA          46845

In [82]:
# Verificando tipo dos dados
media_600.dtypes

uf               object
qtd_media_600     int64
dtype: object

In [83]:
# Salvando df
media_600.to_csv('/content/drive/MyDrive/analise-diagnostico-enem2024/consultas/qtd_media_600.csv', decimal=',', index=False)